
all:
	g++ SalPimienta.cpp -lopencv_core -lopencv_highgui -lopencv_imgproc -lopencv_video -lopencv_videoio -lopencv_imgcodecs -o hola.bin
	
run:
	./hola.bin

	
video:
	g++ EjemploVideo.cpp -lopencv_core -lopencv_highgui -lopencv_imgproc -lopencv_video -lopencv_videoio -lopencv_imgcodecs -o video.bin
	
videor:
	./video.bin
